package com.cbq.brushlessons.core.action.enaea.entity.requirecourselist;

import com.fasterxml.jackson.annotation.JsonProperty;

@lombok.Data
public class ListElement {
    @lombok.Getter(onMethod_ = {@JsonProperty("canRemove")})
    @lombok.Setter(onMethod_ = {@JsonProperty("canRemove")})
    private boolean canRemove;
    @lombok.Getter(onMethod_ = {@JsonProperty("canView")})
    @lombok.Setter(onMethod_ = {@JsonProperty("canView")})
    private boolean canView;
    @lombok.Getter(onMethod_ = {@JsonProperty("circleId")})
    @lombok.Setter(onMethod_ = {@JsonProperty("circleId")})
    private Object circleId;
    @lombok.Getter(onMethod_ = {@JsonProperty("commentCount")})
    @lombok.Setter(onMethod_ = {@JsonProperty("commentCount")})
    private long commentCount;
    @lombok.Getter(onMethod_ = {@JsonProperty("courseId")})
    @lombok.Setter(onMethod_ = {@JsonProperty("courseId")})
    private Object courseId;
    @lombok.Getter(onMethod_ = {@JsonProperty("endTime")})
    @lombok.Setter(onMethod_ = {@JsonProperty("endTime")})
    private Object endTime;
    @lombok.Getter(onMethod_ = {@JsonProperty("homeworkStatus")})
    @lombok.Setter(onMethod_ = {@JsonProperty("homeworkStatus")})
    private Object homeworkStatus;
    @lombok.Getter(onMethod_ = {@JsonProperty("id")})
    @lombok.Setter(onMethod_ = {@JsonProperty("id")})
    private Object id;
    @lombok.Getter(onMethod_ = {@JsonProperty("introduce")})
    @lombok.Setter(onMethod_ = {@JsonProperty("introduce")})
    private Object introduce;
    @lombok.Getter(onMethod_ = {@JsonProperty("isEvaluated")})
    @lombok.Setter(onMethod_ = {@JsonProperty("isEvaluated")})
    private Object isEvaluated;
    @lombok.Getter(onMethod_ = {@JsonProperty("isReAnswer")})
    @lombok.Setter(onMethod_ = {@JsonProperty("isReAnswer")})
    private boolean isReAnswer;
    @lombok.Getter(onMethod_ = {@JsonProperty("isRecommend")})
    @lombok.Setter(onMethod_ = {@JsonProperty("isRecommend")})
    private Object isRecommend;
    @lombok.Getter(onMethod_ = {@JsonProperty("isRequired")})
    @lombok.Setter(onMethod_ = {@JsonProperty("isRequired")})
    private boolean isRequired;
    @lombok.Getter(onMethod_ = {@JsonProperty("liveCourseShowDTO")})
    @lombok.Setter(onMethod_ = {@JsonProperty("liveCourseShowDTO")})
    private Object liveCourseShowDTO;
    @lombok.Getter(onMethod_ = {@JsonProperty("passScore")})
    @lombok.Setter(onMethod_ = {@JsonProperty("passScore")})
    private Object passScore;
    @lombok.Getter(onMethod_ = {@JsonProperty("reAnswerReason")})
    @lombok.Setter(onMethod_ = {@JsonProperty("reAnswerReason")})
    private Object reAnswerReason;
    @lombok.Getter(onMethod_ = {@JsonProperty("remark")})
    @lombok.Setter(onMethod_ = {@JsonProperty("remark")})
    private String remark;
    @lombok.Getter(onMethod_ = {@JsonProperty("resourceId")})
    @lombok.Setter(onMethod_ = {@JsonProperty("resourceId")})
    private Object resourceId;
    @lombok.Getter(onMethod_ = {@JsonProperty("resourceRandomPaperId")})
    @lombok.Setter(onMethod_ = {@JsonProperty("resourceRandomPaperId")})
    private Object resourceRandomPaperId;
    @lombok.Getter(onMethod_ = {@JsonProperty("score")})
    @lombok.Setter(onMethod_ = {@JsonProperty("score")})
    private Object score;
    @lombok.Getter(onMethod_ = {@JsonProperty("scoreTime")})
    @lombok.Setter(onMethod_ = {@JsonProperty("scoreTime")})
    private Object scoreTime;
    @lombok.Getter(onMethod_ = {@JsonProperty("screenName")})
    @lombok.Setter(onMethod_ = {@JsonProperty("screenName")})
    private Object screenName;
    @lombok.Getter(onMethod_ = {@JsonProperty("startTime")})
    @lombok.Setter(onMethod_ = {@JsonProperty("startTime")})
    private Object startTime;
    @lombok.Getter(onMethod_ = {@JsonProperty("studyCenterDTO")})
    @lombok.Setter(onMethod_ = {@JsonProperty("studyCenterDTO")})
    private StudyCenterDTO studyCenterDTO;
    @lombok.Getter(onMethod_ = {@JsonProperty("submitTime")})
    @lombok.Setter(onMethod_ = {@JsonProperty("submitTime")})
    private Object submitTime;
    @lombok.Getter(onMethod_ = {@JsonProperty("supportCount")})
    @lombok.Setter(onMethod_ = {@JsonProperty("supportCount")})
    private long supportCount;
    @lombok.Getter(onMethod_ = {@JsonProperty("syllabusResourceId")})
    @lombok.Setter(onMethod_ = {@JsonProperty("syllabusResourceId")})
    private long syllabusResourceId;
    @lombok.Getter(onMethod_ = {@JsonProperty("teacherName")})
    @lombok.Setter(onMethod_ = {@JsonProperty("teacherName")})
    private String teacherName;
    @lombok.Getter(onMethod_ = {@JsonProperty("thesisStatus")})
    @lombok.Setter(onMethod_ = {@JsonProperty("thesisStatus")})
    private Object thesisStatus;
    @lombok.Getter(onMethod_ = {@JsonProperty("title")})
    @lombok.Setter(onMethod_ = {@JsonProperty("title")})
    private Object title;
    @lombok.Getter(onMethod_ = {@JsonProperty("totalScore")})
    @lombok.Setter(onMethod_ = {@JsonProperty("totalScore")})
    private Object totalScore;
}
