package com.cbq.yatori.core.action.yinghua.entity.examinform;

import com.fasterxml.jackson.annotation.JsonProperty;

@lombok.Data
public class ListElement {
    @lombok.Getter(onMethod_ = {@JsonProperty("addDate")})
    @lombok.Setter(onMethod_ = {@JsonProperty("addDate")})
    private String addDate;
    @lombok.Getter(onMethod_ = {@JsonProperty("addTime")})
    @lombok.Setter(onMethod_ = {@JsonProperty("addTime")})
    private String addTime;
    @lombok.Getter(onMethod_ = {@JsonProperty("allow")})
    @lombok.Setter(onMethod_ = {@JsonProperty("allow")})
    private String allow;
    @lombok.Getter(onMethod_ = {@JsonProperty("classList")})
    @lombok.Setter(onMethod_ = {@JsonProperty("classList")})
    private String classList;
    @lombok.Getter(onMethod_ = {@JsonProperty("courseId")})
    @lombok.Setter(onMethod_ = {@JsonProperty("courseId")})
    private Long courseId;
    @lombok.Getter(onMethod_ = {@JsonProperty("createUserId")})
    @lombok.Setter(onMethod_ = {@JsonProperty("createUserId")})
    private String createUserId;
    @lombok.Getter(onMethod_ = {@JsonProperty("endTime")})
    @lombok.Setter(onMethod_ = {@JsonProperty("endTime")})
    private String endTime;
    @lombok.Getter(onMethod_ = {@JsonProperty("finish")})
    @lombok.Setter(onMethod_ = {@JsonProperty("finish")})
    private Long finish;
    @lombok.Getter(onMethod_ = {@JsonProperty("flag")})
    @lombok.Setter(onMethod_ = {@JsonProperty("flag")})
    private Long flag;
    @lombok.Getter(onMethod_ = {@JsonProperty("frequency")})
    @lombok.Setter(onMethod_ = {@JsonProperty("frequency")})
    private String frequency;
    @lombok.Getter(onMethod_ = {@JsonProperty("hasCollect")})
    @lombok.Setter(onMethod_ = {@JsonProperty("hasCollect")})
    private String hasCollect;
    @lombok.Getter(onMethod_ = {@JsonProperty("id")})
    @lombok.Setter(onMethod_ = {@JsonProperty("id")})
    private Long id;
    @lombok.Getter(onMethod_ = {@JsonProperty("isPrivate")})
    @lombok.Setter(onMethod_ = {@JsonProperty("isPrivate")})
    private String isPrivate;
    @lombok.Getter(onMethod_ = {@JsonProperty("limitedTime")})
    @lombok.Setter(onMethod_ = {@JsonProperty("limitedTime")})
    private Long limitedTime;
    @lombok.Getter(onMethod_ = {@JsonProperty("nodeId")})
    @lombok.Setter(onMethod_ = {@JsonProperty("nodeId")})
    private Long nodeId;
    @lombok.Getter(onMethod_ = {@JsonProperty("parsing")})
    @lombok.Setter(onMethod_ = {@JsonProperty("parsing")})
    private String parsing;
    @lombok.Getter(onMethod_ = {@JsonProperty("randData")})
    @lombok.Setter(onMethod_ = {@JsonProperty("randData")})
    private Object randData;
    @lombok.Getter(onMethod_ = {@JsonProperty("randNumber")})
    @lombok.Setter(onMethod_ = {@JsonProperty("randNumber")})
    private String randNumber;
    @lombok.Getter(onMethod_ = {@JsonProperty("random")})
    @lombok.Setter(onMethod_ = {@JsonProperty("random")})
    private String random;
    @lombok.Getter(onMethod_ = {@JsonProperty("remarks")})
    @lombok.Setter(onMethod_ = {@JsonProperty("remarks")})
    private String remarks;
    @lombok.Getter(onMethod_ = {@JsonProperty("schoolId")})
    @lombok.Setter(onMethod_ = {@JsonProperty("schoolId")})
    private String schoolId;
    @lombok.Getter(onMethod_ = {@JsonProperty("score")})
    @lombok.Setter(onMethod_ = {@JsonProperty("score")})
    private Long score;
    @lombok.Getter(onMethod_ = {@JsonProperty("start")})
    @lombok.Setter(onMethod_ = {@JsonProperty("start")})
    private Long start;
    @lombok.Getter(onMethod_ = {@JsonProperty("startTime")})
    @lombok.Setter(onMethod_ = {@JsonProperty("startTime")})
    private String startTime;
    @lombok.Getter(onMethod_ = {@JsonProperty("teacherType")})
    @lombok.Setter(onMethod_ = {@JsonProperty("teacherType")})
    private String teacherType;
    @lombok.Getter(onMethod_ = {@JsonProperty("title")})
    @lombok.Setter(onMethod_ = {@JsonProperty("title")})
    private String title;
    @lombok.Getter(onMethod_ = {@JsonProperty("topicNumber")})
    @lombok.Setter(onMethod_ = {@JsonProperty("topicNumber")})
    private Long topicNumber;
    @lombok.Getter(onMethod_ = {@JsonProperty("type")})
    @lombok.Setter(onMethod_ = {@JsonProperty("type")})
    private Long type;
    @lombok.Getter(onMethod_ = {@JsonProperty("url")})
    @lombok.Setter(onMethod_ = {@JsonProperty("url")})
    private String url;
}
